schibsted/account-sdk-browser

src/identity.js
Fixes #23
The Schibsted Account backend seems to not care about the redirect_uri
parameter, so I’m not sure why it was ever in the SDK in the first
place.
=> Remove redirectUri parameter from Identity.logout

README.md, __tests__/url.utest.js, package-lock.json, package.json, src/url.js
Rework how our urlMapper helper function works to work around polyfilling issues, as mentioned in #31
=> IE related fixes

src/identity.js
It was unclear that hasSession might automatically perform a login on a
user behind the scenes. Also, it was unclear that this side-effect could
also happen for any function calling hasSession internally.
=> docs: Update hasSession doc and all functions calling hasSession

README.md, __mocks__/fetch-jsonp.js, __tests__/identity.js, src/identity.js
Removed from server responses, so we should not depend on it anymore.
=> Remove visitor

__tests__/identity.js, src/identity.js, src/validate.js
* Ensure our Identity.getUserId and .getUserUuid follows the documented behaviour (that we throw if the user is not connected to the merchant).
* Clean up some outdated todo comments
=> Fix Identity.getUserId, .getUserUuid and some cleanup

CHANGELOG.md, package-lock.json, package.json, src/identity.js
Fixes https://github.com/schibsted/account-sdk-browser/issues/62
=> Remove hasSession cache on login method.

__tests__/identity.js, src/identity.js
=> Clear the varnish cookie on logout

__tests__/identity.js, src/identity.js
All of those params will be passed via oauth service to bff. Old flows supports teaser and tag
=> Add new params to login: tag, teaser, maxAge

src/identity.js
=> Make sure logging in works on non-Safari iOS browsers

__tests__/url.utest.js, src/identity.js, src/url.js
=> Extract top domain and use that when setting SP_ID cookie

__tests__/identity.js, __tests__/url.utest.js, jest.config.js, src/identity.js, src/url.js
* remove getTopDomain that didn't get called on login, only on logout
* add `domain` option to `enableVarnishCookie`
resolves https://github.com/schibsted/account-sdk-browser/issues/98
=> replace getTopDomain with enableVarnishCookie domain option

__tests__/identity.js, src/identity.js
This depends on new site-specific logout endpoint in session-service, so don't merge yet 🙂
=> Site-specific logout

__tests__/identity.js, src/identity.js
Will load simplified login widget, and display it on page
=> showSimplifiedLoginWidget function

src/identity.js
Which haven't been cached before...
=> Cache session service failure requests

src/identity.js
Added support to forward providerId from usercontext to simplified login widget
=> Added support for providerId when triggering simplified login

__tests__/identity.js, __tests__/monetization.js, src/identity.js, src/monetization.js
=> Add methods for clearing cached data

.travis.yml, __tests__/identity.js, __tests__/monetization.js, package-lock.json, package.json
Fixes problems with vulnerable dependencies.
=> Updated packages to fix security vulnerabilities

identity.d.ts, index.d.ts, monetization.d.ts, payment.d.ts, src/RESTClient.d.ts, src/RESTClient.js, src/SDKError.d.ts, src/cache.d.ts, src/config.d.ts, src/es5/index.d.ts, src/identity.d.ts, src/identity.js, src/monetization.d.ts, src/monetization.js, src/object.d.ts, src/payment.d.ts, src/payment.js, src/popup.d.ts, src/spidTalk.d.ts, src/url.d.ts, src/validate.d.ts, src/validate.js
Autogenerated via ts (` npx tsc index.js --allowJs --emitDeclarationOnly -d`)
=> Add .d.ts files

identity.d.ts, monetization.d.ts, payment.d.ts, src/identity.d.ts, src/identity.js
Support for non-default exports in typescript definition files.
=> Fixed typescript exports

src/identity.d.ts, src/identity.js
=> fix: typing enableVarnishCookie option.domain should be string

README.md, __tests__/identity.js, src/identity.d.ts, src/identity.js
Possibility to specify encoding on SimplifiedLoginWidget
=> Added encoding param to showSimplifiedLoginWidget function

.npmignore, index.d.ts
=> fix: publish more typings

README.md, __tests__/identity.js, src/identity.d.ts, src/identity.js
Because of https://github.schibsted.io/spt-identity/t/issues/1782
Should be merged when it's actually fully working underneath :)
=> Support eid-se acr value.

README.md, __tests__/identity.js, package-lock.json, src/identity.d.ts, src/identity.js
Because of https://github.schibsted.io/spt-identity/t/issues/1585
Should be merged when it's actually fully working underneath :)
=> Support eid-no acr value

__tests__/identity.js, src/identity.js
Add `eid-fi` as allowed acrValues
=> Add eid-fi support for acrValues

.travis.yml, __tests__/identity.js, __tests__/monetization.js, __tests__/payment.js, build.sh
Required to unblock work on: https://github.com/schibsted/account-sdk-browser/pull/243
=> Use NodeJS 18 environment to build package

src/identity.d.ts
=> docs: dts update

__tests__/identity.js, src/identity.d.ts, src/identity.js
This release contains only tabid changes compared to version 5.0.0
=> Prepare release 5.0.1

__tests__/identity.js, src/identity.d.ts, src/identity.js
This PR's aim is only to undo the previous 2 reverts that were done to allow release of 5.0.1 version
=> Add back local storage changes

MIGRATION.md
Small refactor of the migration guide.
Changed formatting and wording, and also added some more details about the whole ITP flow.
=> docs: update MIGRATION.md

__tests__/identity.js, src/identity.d.ts, src/identity.js
Adding optional param for cross-domain tracking
=> feat: x-domain-id param

CHANGELOG.md, MIGRATION.md, package-lock.json, package.json, src/version.js
=> Bump version

CHANGELOG.md, package-lock.json, package.json, src/version.js
=> Deploy new version
