__tests__/.eslintrc.yml, __tests__/identity.js, src/identity.js
Version 2.x of this SDK has a check that if a return value from
hasSession contains an “error” key with child “type”: “LoginException”,
it will repeat the request, but send it directly to SPiD.
There was a bug in this version. A call to fetch only errors when there
is a network error, so the error handling to check for “LoginException”
was placed in the wrong spot. I have moved it, and also created a unit
test to simulate this and verify that such a response from hasSession
should in fact retry the request to SPiD.
Thanks to Terje Andersen for reporting the bug.
=> Teach Identity.hasSession to fall back to spid

src/identity.js
The `loginHint` parameter belongs under `options`. Also, added the
default value for the `redirectUri` option.
=> identity: Fix documentation issues on login(..)

__tests__/RESTClient.utest.js, src/RESTClient.js
This issue was only discovered when communicating with the BFF, but
without this commit, the fetch command will fail in certain browsers,
because they need it to be bound to the window instance.
=> RESTClient: Bind default fetch reference to ‘window’

README.md, src/identity.js
Fixes #22
I am experiencing the same as fredrikstave who reported this issue, that
it works when you are on a “real” domain, but not when you are on
localhost (tested in Safari and Chrome so far). So let’s make this clear
in the docs.
=> doc: enableVarnishCookie requires origin != localhost

src/identity.js
During the 2.5 hours when a site went live yesterday, we saw some errors
that the logout() requests were failing. This was because they were
calling it from a http origin, and only the https origin was listed in
redirect_uris.
=> doc: Clarify that Identity.logout() validates CORS

.npmignore
Fixes #38
When we generate ES5 compatible files, there were no source maps
included. Should work fine now.
=> npmignore: include source maps for es5 files

__tests__/cache.js, __tests__/identity.js, src/cache.js, src/identity.js
Fixes #40 
There were two things happening here:
1. The events were not being emitted when we used values from the cache 🤦‍♂️
1. The cache had a `setTimeout` that would remove cached items after an `expiresIn` amount of milliseconds (coming from the Schibsted account backend). When Safari is used, the backend sends 2592000000 (30 days), which exceeds the maximum value for `setTimeout` and in this case, it executes immediately.
=> hassession: emit proper events and ensure caching works properly

src/RESTClient.js, src/identity.js, src/monetization.js, src/payment.js
Fixes #41 (I hope..)
This was an issue for people using server-side rendering, where simply
importing a file will break when there are references to window at the
root level of a file.
=> Remove refs to ‘window’ from global scope

.eslintrc.yml, src/RESTClient.js, src/identity.js, src/monetization.js, src/payment.js, src/validate.js
We want docs for exported functions, sure, but it’s overkill to demand
it for small helpers. When the source gets scattered with eslint-disable
stuff, it’s a good sign that rules should be changed I think.
=> Lax require-jsdoc eslint rule for arrow functions

src/es5/global.js
This file was not working well, since it didn’t assign
window.regeneratorRuntime before attempting to load Identity,
Monetization and Payment. D’oh! This commit simplifies how it works, by
reusing what happens in index.js.
=> es5: Ensure regeneratorRuntime is available

__tests__/payment.js, package-lock.json, src/RESTClient.js, src/payment.js
for now building purchase flow uri ends with params filled with null values like `voucher_code=null`
from now on default null values should be ingored
=> ignore null params when constructing uri

__tests__/identity.js, src/identity.js
Fixes #68
Bah! The Identity.logout() and Identity.enableVarnishCookie() functions
both called _initCache which doesn’t clear the existing key from
localStorage. This caused these function to *think* the cache was
cleared, when in fact it wasn’t. Weirdness ensues… Issue is fixed and a
test was added to make sure it doesn’t happen again.
=> Ensure we clear cache when logging out

README.md, __tests__/identity.js, src/identity.js
We can’t rely on XHRs working after Safari 12. VG showed that it doesn’t
work correctly on the SPiD side, although I don’t fully understand why.
What we observe is:
1) Log in from VG
2) Log out from VG (observe that the Network tab has requests going to
/ajax/logout.js and /authn/identity/logout — both returning 200. This
makes VG of course show you as logged out
3) Log in again. Observe that you are (wrongly) automatically logged in
with no need for authentication
Since we want to move away from XHRs relying on 3rd party cookies
anyway, this commit changes the way it works by doing a full-page
redirect (after cleaning up cache/varnish cookie) instead. Since there
are no requests being sent in logout() anymore, I removed the async
modifier, even though this is a breaking change.
=> Change the logout function to do full-page redirect

__tests__/identity.js, src/RESTClient.js, src/identity.js
The most important change is https://github.com/schibsted/account-sdk-browser/compare/add-locale-param-to-login?expand=1#diff-b8139375bef5ea9da4706270fef9c716R183 . I believe that it shouldn't have big influence since it will skip only empty string query params.
=> Add locale param to login

src/SDKError.js
silently catch errors from Object.assign in SDKError
fixes https://github.com/schibsted/account-sdk-browser/issues/101
=> silently catch errors from Object.assign in SDKError

src/identity.js
We have struggled with bad performance in terms of prolonged script evaluation in Internet Explorer 11 and tracked it down to https://github.com/schibsted/account-sdk-browser/blob/master/src/identity.js#L485 being the issue.
Instead of throwing an error in `postProcess`, we first emit an error event (not sure if needed), like it does in the catch block, then reject.
This resulted in script evaluation going from 20-30s to 1.5-3s in IE11.
=> fix(src): reject in hasSession

src/payment.js
@fixes https://github.com/schibsted/account-sdk-browser/issues/94
=> Mark purchasePaylinkUrl as depracated

__tests__/identity.js, src/config.js, src/identity.js
To enable the brand sites to contexutalise continue-as/simplified-login
prompts.
~*Note:* This depends on a new endpoint in session-service (not yet deployed), so don't merge yet. 🙂~
=> Add Identity function to get user context data.

__tests__/identity.js, src/identity.js
The errors and symptoms we fix here are very similar to the ones tackled in #112.
IE11 chokes on the current setup with an asynchronous Promise executor
under certain circumstances. This change utilizes asynchronous functions
instead to achieve the same functionality as before.
Additionally, it simplifies logic slightly by reorganizing internal error
handling, event triggering and session data post processing.
=> fix: remove Promise constructor in `hasSession`

__tests__/identity.js, src/identity.js
It was deprecated and removed 16th Aug 2020 and the 'new-flow=true'
parameter is no longer required.
=> Remove support for old login flows

src/identity.d.ts, src/identity.js
New parameter in v4.4.0 breaks any existing implementation of showSimplifiedLoginWidget since the new option is not specified as optional even tho the code expects it to be optional
=> simplifiedLoginWidget options should be optional

src/payment.d.ts, src/payment.js
Clients should not use that function anymore, they should generate urls on their own (as for now).
=> Marked purchasePromoCodeProductFlowUrl as deprecated

src/identity.d.ts, src/identity.js
Should resolve issue with different type of state for Login and showSimplifiedLoginWidget
It doesn't look like JSDoc supports any type of intersection or extension, so the only way I could make it work was to declare everything twice. Please let me know if you have a better way.
=> docs: fix login-types

README.md
Travis CI is available under the new location - link in `README.md` was outdated
=> Update link to Travis CI

README.md
Cleaned up the readme a bit.
Session service is required nowadays and we don't need to explain ITP.
No value in having a huge block of text covering migrating from old version of sdk since that has not been in use for many years now.
Moved polyfills section to appendix.
=> Removed irrelevant info and cleaned up readme

src/identity.d.ts
Class Identity extends EventEmitter in the JS file, but it's not typed for TS.
=> fix: improve Identity types

CHANGELOG.md, package-lock.json, package.json
When releasing 4.7.4 last month, I created the GIT release, but forgot to update package.json and the release didn't push to NPM. This change should fix that
=> release 4.7.4

.eslintrc.yml, __tests__/RESTClient.intest.js, __tests__/RESTClient.utest.js, __tests__/SDKError.js, __tests__/cache.js, __tests__/identity.js, __tests__/monetization.js, __tests__/object.utest.js, __tests__/payment.js, __tests__/popup.js, __tests__/spidTalk.js, __tests__/testutils.utest.js, __tests__/url.utest.js, __tests__/validate.utest.js, src/RESTClient.js, src/__mocks__/RESTClient.js, src/cache.js, src/identity.js, src/monetization.js, src/object.js, src/payment.js, src/popup.js, src/spidTalk.js, src/url.js, src/validate.js
Importing the SDK as real ESM does not work due to
1) Missing file extension
2) Importing json
=> Fix for using SDK as ESM

__tests__/identity.js, package.json, scripts/genversion.js, src/identity.js, src/monetization.js, src/version.d.ts, src/version.js
Including json files in ESM is messy, especially if not running webpack that can resolve files.
Including the package.json also means it gets included in the built file, which likely is not what we want.
This PR generates are version file when you run `npm version` and adds it to the tagged commit.
=> Generate version file instead of including pkg.json

__tests__/identity.js, src/identity.js
Description:
This PR adds 2 new events:
- `simplifiedLoginOpened` emitted when the widget loaded
- `simplifiedLoginCancelled` emitted when the user closes the widget without logging in
=> Add open & cancel events to SimplifiedLoginWidget

src/identity.d.ts, src/monetization.d.ts, src/payment.d.ts
When working with TypeScript set to handle NodeNext modules 
```json
"compilerOptions": {
"moduleResolution": "NodeNext",
"module": "NodeNext",
```
There are compilation errors as below:
> TS2835: Relative import paths need explicit file extensions in EcmaScript imports when  --moduleResolution  is  node16  or  nodenext . Did you mean  ./SDKError.js ?
=> fix: ES modules import in TS files

package-lock.json, package.json, src/identity.js, src/version.js
If brands are adding Identity calls in either callback or on page load lifecycle, calls can happen in parallel, leading to some calls taking place without the correct cookies and leading to user logout.
Moving navigation to hasSessionInProgress to  `getSession().then` seems to have fixed this problem
=> move navigation in hasSessionInProgress

__tests__/identity.js, src/identity.js
This PR adds a simple mechanism for creating tab-scoped IDs that are persistent after redirects.
Flow goes as follows:
page-load -> generate ID -> try to store ID in session storage if it's not present already -> session flow -> redirect -> read ID from session storage
We need this in order to debug a race condition bug causing logouts.
Tested locally using PRE env so logs confirm it works.
=> feat: add tabId to refresh-itp-cookies

__tests__/identity.js, src/identity.js
Moving `sessionCallBlocked-cache` to local storage to allow it to be used across bowser tabs
=> move session call lock to local storage

src/cache.js, src/identity.d.ts, src/identity.js
Fixes a bug regarding cache being no longer defined due to the split to localStorage and sessionStorage.
Additionally, adds missing methods to identity.d.ts
=> Rename cache instance and update dts

README.md
Removed documentation example mentioning polyfill.io due to supply chain attack.
=> docs: remove polyfill example

__tests__/identity.js, src/RESTClient.js, src/identity.js
If session-service is pathed, web-sdk should call the previous get session endpoint. If it's not, it should call the v2 get session endpoint.
Also:
In the past there were a few problems with either endpoints or client domains being defined internally in a way that URL doesn't support, leading to unpredictable behaviour.
Added string formatting to ensure domains and endpoints will play nice with `new URL`
=> Use get session endpoint conditionally if session-service is pathed
